// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateWeb.Data;

#nullable disable

namespace RealEstateWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250922163601_SeedPropertyData")]
    partial class SeedPropertyData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateWeb.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Đường Lê Lợi, Quận 1, TP.HCM",
                            Description = "Nhà đẹp trung tâm Quận 1",
                            ImageUrl = "/img/nhaphoquan1.jpg",
                            Price = 5000000000m,
                            Title = "Nhà phố Quận 1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Đường Nguyễn Văn Linh, Quận 7, TP.HCM",
                            Description = "Căn hộ view sông Quận 7",
                            ImageUrl = "/img/canhoquan7.jpg",
                            Price = 2000000000m,
                            Title = "Căn hộ Quận 7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
