// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateWeb.Data;

#nullable disable

namespace RealEstateWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250923163227_AddPropertyExtraFields")]
    partial class AddPropertyExtraFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateWeb.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bath")
                        .HasColumnType("int");

                    b.Property<int>("Bed")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Street, New York, USA",
                            Bath = 2,
                            Bed = 3,
                            Description = "Nhà phố đẹp, trung tâm thành phố, nội thất cao cấp.",
                            ImageUrl = "/img/property-1.jpg",
                            Price = 12345000m,
                            Size = 1000,
                            Status = "For Sell",
                            Title = "Golden Urban House For Sell",
                            Type = "Apartment"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Avenue, Los Angeles, USA",
                            Bath = 4,
                            Bed = 5,
                            Description = "Biệt thự sang trọng, view sông, đầy đủ tiện nghi.",
                            ImageUrl = "/img/property-2.jpg",
                            Price = 8500000m,
                            Size = 2500,
                            Status = "For Rent",
                            Title = "Luxury Villa For Rent",
                            Type = "Villa"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Business Rd, Chicago, USA",
                            Bath = 2,
                            Bed = 0,
                            Description = "Văn phòng hiện đại nằm tại khu business district.",
                            ImageUrl = "/img/property-3.jpg",
                            Price = 4500000m,
                            Size = 1500,
                            Status = "For Sell",
                            Title = "Modern Office Space",
                            Type = "Office"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
